version: '1.0'
app:
  bundleId: com.google.Chrome
  name: Google Chrome
  displayName: Google Chrome
  tccEntitlements:
    - automation
  distributionModel: system
suites:
  - name: Standard Suite
    code: core
    description: Common classes and commands for all applications.
    resources:
      - Window
    commands:
      - save
      - open
      - close
      - quit
      - count
      - delete
      - duplicate
      - exists
      - make
      - move
      - print
  - name: Chromium Suite
    code: CrSu
    description: Common classes and commands for Chrome.
    resources:
      - Tab
      - BookmarkFolder
      - BookmarkItem
    commands:
      - reload
      - goBack
      - goForward
      - selectAll
      - cutSelection
      - copySelection
      - pasteSelection
      - undo
      - redo
      - stop
      - viewSource
      - execute
resources:
  Window:
    name: Window
    plural: Windows
    description: A window.
    code: cwin
    properties:
      givenName:
        access: rw
        type: string
        description: The given name of the window.
        code: GNam
      name:
        access: r
        type: string
        description: The full title of the window.
        code: pnam
      id:
        access: r
        type: string
        description: The unique identifier of the window.
        code: 'ID  '
      index:
        access: rw
        type: integer
        description: The index of the window, ordered front to back.
        code: pidx
      bounds:
        access: rw
        type: rect
        description: The bounding rectangle of the window.
        code: pbnd
      closeable:
        access: r
        type: boolean
        description: Whether the window has a close box.
        code: hclb
      minimizable:
        access: r
        type: boolean
        description: Whether the window can be minimized.
        code: ismn
      minimized:
        access: rw
        type: boolean
        description: Whether the window is currently minimized.
        code: pmnd
      resizable:
        access: r
        type: boolean
        description: Whether the window can be resized.
        code: prsz
      visible:
        access: rw
        type: boolean
        description: Whether the window is currently visible.
        code: pvis
      zoomable:
        access: r
        type: boolean
        description: Whether the window can be zoomed.
        code: iszm
      zoomed:
        access: rw
        type: boolean
        description: Whether the window is currently zoomed.
        code: pzum
      activeTab:
        access: r
        type:
          resource: tab
        description: Returns the currently selected tab
        code: acTa
      mode:
        access: rw
        type: string
        description: Represents the mode of the window which can be 'normal' or 'incognito', can be set only once during creation of the window.
        code: mode
      activeTabIndex:
        access: rw
        type: integer
        description: The index of the active tab.
        code: acTI
    identifiers:
      - property: id
        primary: true
  Tab:
    name: Tab
    plural: Tabs
    description: A tab.
    code: CrTb
    properties:
      id:
        access: r
        type: string
        description: Unique ID of the tab.
        code: 'ID  '
      title:
        access: r
        type: string
        description: The title of the tab.
        code: pnam
      uRL:
        access: rw
        type: string
        description: The url visible to the user.
        code: 'URL '
      loading:
        access: r
        type: boolean
        description: Is loading?
        code: ldng
    identifiers:
      - property: id
        primary: true
  BookmarkFolder:
    name: BookmarkFolder
    plural: BookmarkFolders
    description: A bookmarks folder that contains other bookmarks folder and bookmark items.
    code: CrBF
    properties:
      id:
        access: r
        type: string
        description: Unique ID of the bookmark folder.
        code: 'ID  '
      title:
        access: rw
        type: string
        description: The title of the folder.
        code: pnam
      index:
        access: r
        type: number
        description: Returns the index with respect to its parent bookmark folder.
        code: pidx
    identifiers:
      - property: id
        primary: true
  BookmarkItem:
    name: BookmarkItem
    plural: BookmarkItems
    description: An item consists of an URL and the title of a bookmark
    code: CrBI
    properties:
      id:
        access: r
        type: string
        description: Unique ID of the bookmark item.
        code: 'ID  '
      title:
        access: rw
        type: string
        description: The title of the bookmark item.
        code: pnam
      uRL:
        access: rw
        type: string
        description: The URL of the bookmark.
        code: 'URL '
      index:
        access: r
        type: number
        description: Returns the index with respect to its parent bookmark folder.
        code: pidx
    identifiers:
      - property: id
        primary: true
enums: {}

hierarchy:
  children:
    bookmarkFolders:
      resource: BookmarkFolder
      access: r
      description: A bookmarks folder that contains other bookmarks folder and bookmark items.
      children:
        bookmarkItems:
          resource: BookmarkItem
          access: rw
          description: An item consists of an URL and the title of a bookmark
commands:
  save:
    name: save
    description: Save an object.
    scope: application
    code: save
    parameters:
      - name: in
        type: file
        description: The file in which to save the object.
        required: false
        code: kfil
      - name: as
        type: string
        description: The file type in which to save the data. Can be 'only html', 'complete html', or 'single file'; default is 'complete html'.
        required: false
        code: fltp
  open:
    name: open
    description: Open a document.
    scope: application
    code: odoc
    parameters: []
  close:
    name: close
    description: Close a window.
    scope: application
    code: clos
    parameters: []
  quit:
    name: quit
    description: Quit the application.
    scope: application
    code: quit
    parameters: []
  count:
    name: count
    description: Return the number of elements of a particular class within an object.
    scope: application
    code: cnte
    parameters:
      - name: each
        type: string
        description: The class of objects to be counted.
        required: false
        code: kocl
  delete:
    name: delete
    description: Delete an object.
    scope: application
    code: delo
    parameters: []
  duplicate:
    name: duplicate
    description: Copy object(s) and put the copies at a new location.
    scope: application
    code: clon
    parameters:
      - name: to
        type: string
        description: The location for the new object(s).
        required: false
        code: insh
      - name: withProperties
        type: any
        description: Properties to be set in the new duplicated object(s).
        required: false
        code: prdt
  exists:
    name: exists
    description: Verify if an object exists.
    scope: application
    code: doex
    parameters: []
  make:
    name: make
    description: Make a new object.
    scope: application
    code: crel
    parameters:
      - name: new
        type: string
        description: The class of the new object.
        required: true
        code: kocl
      - name: at
        type: string
        description: The location at which to insert the object.
        required: false
        code: insh
      - name: withData
        type: any
        description: The initial contents of the object.
        required: false
        code: data
      - name: withProperties
        type: any
        description: The initial values for properties of the object.
        required: false
        code: prdt
  move:
    name: move
    description: Move object(s) to a new location.
    scope: application
    code: move
    parameters:
      - name: to
        type: string
        description: The new location for the object(s).
        required: true
        code: insh
  print:
    name: print
    description: Print an object.
    scope: application
    code: pdoc
    parameters: []
  reload:
    name: reload
    description: Reload a tab.
    scope: application
    code: Rlod
    parameters: []
  goBack:
    name: goBack
    description: Go Back (If Possible).
    scope: application
    code: Back
    parameters: []
  goForward:
    name: goForward
    description: Go Forward (If Possible).
    scope: application
    code: 'Fwd '
    parameters: []
  selectAll:
    name: selectAll
    description: Select all.
    scope: application
    code: SlAl
    parameters: []
  cutSelection:
    name: cutSelection
    description: Cut selected text (If Possible).
    scope: application
    code: 'Cut '
    parameters: []
  copySelection:
    name: copySelection
    description: Copy text.
    scope: application
    code: 'Cop '
    parameters: []
  pasteSelection:
    name: pasteSelection
    description: Paste text (If Possible).
    scope: application
    code: Past
    parameters: []
  undo:
    name: undo
    description: Undo the last change.
    scope: application
    code: Undo
    parameters: []
  redo:
    name: redo
    description: Redo the last change.
    scope: application
    code: Redo
    parameters: []
  stop:
    name: stop
    description: Stop the current tab from loading.
    scope: application
    code: stop
    parameters: []
  viewSource:
    name: viewSource
    description: View the HTML source of the tab.
    scope: application
    code: VSrc
    parameters: []
  execute:
    name: execute
    description: Execute a piece of javascript.
    scope: application
    code: ExJa
    parameters:
      - name: javascript
        type: string
        description: The javascript code to execute.
        required: true
        code: JvSc
