packages:
  - packages/*
  - manifests/*
  - benchmarks/*
  - e2e/*

catalog:
  clipanion: ^4.0.0-rc.4
  tsd: ^0.31.2
  tsup: ^8.5.1
  typanion: ^3.14.0
  typescript: 5.9.3
  vitest: ^3.1.0
  yaml: ^2.7.0
  zod: ^4.3.6

onlyBuiltDependencies:
  - '@withgraphite/graphite-cli'
  - better-sqlite3
  - esbuild
  - nx

patchedDependencies:
  thread-stream@4.0.0: patches/thread-stream@4.0.0.patch
