version: '1.0'
app:
  bundleId: com.apple.Safari
  name: Safari
  displayName: Safari
  tccEntitlements:
    - automation
  distributionModel: system
suites:
  - name: Safari suite
    code: sfri
    description: Safari specific classes
    resources:
      - Document
      - Tab
    commands:
      - addReadingListItem
      - doJavaScript
      - emailContents
      - searchTheWeb
      - showBookmarks
      - showExtensionsPreferences
      - dispatchMessageToExtension
      - syncAllPlistToDisk
      - showPrivacyReport
      - showCreditCardSettings
resources:
  Document:
    name: Document
    plural: Documents
    description: A Safari document (window)
    code: docu
    properties:
      name:
        access: r
        type: string
        description: The document name
        code: pnam
      id:
        access: r
        type: string
        description: The unique identifier of the document
        code: 'ID  '
      url:
        access: rw
        type: string
        description: The current URL
        code: 'URL '
    identifiers:
      - property: id
        primary: true
  Tab:
    name: Tab
    plural: Tabs
    description: A Safari tab
    code: 'tab '
    properties:
      name:
        access: r
        type: string
        description: The tab name
        code: pnam
      id:
        access: r
        type: string
        description: The unique identifier of the tab
        code: 'ID  '
      url:
        access: rw
        type: string
        description: The tab URL
        code: 'URL '
      source:
        access: r
        type: string
        description: The HTML source of the web page currently loaded in the tab
        code: 'src '
      text:
        access: r
        type: string
        description: The text of the web page currently loaded in the tab
        code: text
    identifiers:
      - property: id
        primary: true
enums: {}
hierarchy:
  children:
    documents:
      resource: Document
      access: rw
      description: Safari documents
      children:
        tabs:
          resource: Tab
          access: rw
          description: Tabs in a document
    tabs:
      resource: Tab
      access: rw
      description: All tabs
commands:
  addReadingListItem:
    name: addReadingListItem
    description: Add a new Reading List item with the given URL. Allows a custom title and preview text to be specified.
    scope: application
    code: arli
    parameters:
      - name: andPreviewText
        type: string
        description: Preview text for the Reading List item, usually the first few sentences of the article
        required: false
        code: rlip
      - name: withTitle
        type: string
        description: Title of the Reading List item
        required: false
        code: rlit
  doJavaScript:
    name: doJavaScript
    description: Applies a string of JavaScript code to a document.
    scope: application
    code: dojs
    parameters:
      - name: in
        type: string
        description: The tab that the JavaScript should be evaluated in.
        required: false
        code: dcnm
  emailContents:
    name: emailContents
    description: Emails the contents of a tab.
    scope: application
    code: mlct
    parameters:
      - name: of
        type: string
        description: The tab to send.
        required: false
        code: dcnm
  searchTheWeb:
    name: searchTheWeb
    description: Searches the web using Safari's current search provider.
    scope: application
    code: srch
    parameters:
      - name: in
        type: string
        description: The tab that the search results should shown in.
        required: false
        code: dcnm
      - name: for
        type: string
        description: The query to search for.
        required: true
        code: qury
  showBookmarks:
    name: showBookmarks
    description: Shows Safari's bookmarks.
    scope: application
    code: opbk
    parameters: []
  showExtensionsPreferences:
    name: showExtensionsPreferences
    description: Show Safari Extensions preferences.
    scope: application
    code: ssep
    parameters: []
  dispatchMessageToExtension:
    name: dispatchMessageToExtension
    description: Dispatch a message to a Safari Extension.
    scope: application
    code: dste
    parameters: []
  syncAllPlistToDisk:
    name: syncAllPlistToDisk
    description: Make sure that all in-memory structures are in-sync with their on-disk counterparts.
    scope: application
    code: plst
    parameters: []
  showPrivacyReport:
    name: showPrivacyReport
    description: Show Safari's Privacy Report
    scope: application
    code: pvrp
    parameters: []
  showCreditCardSettings:
    name: showCreditCardSettings
    description: Show Safari Credit Card Settings.
    scope: application
    code: sccs
    parameters: []
