version: '1.0'
app:
  bundleId: com.apple.MobileSMS
  name: Messages
  displayName: Messages
  tccEntitlements:
    - automation
  distributionModel: system
suites:
  - name: Messages Suite
    code: icht
    description: commands and classes for Messages scripting.
    resources:
      - Participant
      - Account
      - Chat
    enums:
      - ServiceType
      - Direction
      - TransferStatus
      - ConnectionStatus
    commands:
      - send
      - login
      - logout
resources:
  Participant:
    name: Participant
    plural: Participants
    description: A participant for an account.
    code: pres
    properties:
      id:
        access: r
        type: string
        description: "The participant's unique identifier. For example: 01234567-89AB-CDEF-0123-456789ABCDEF:+11234567890"
        code: 'ID  '
      account:
        access: r
        type:
          resource: account
        description: The account for this participant.
        code: icsv
      name:
        access: r
        type: string
        description: The participant's name as it appears in the participant list.
        code: pnam
      handle:
        access: r
        type: string
        description: The participant's handle.
        code: hndl
      firstName:
        access: r
        type: string
        description: The first name from this participan's Contacts card, if available
        code: prfn
      lastName:
        access: r
        type: string
        description: The last name from this participant's Contacts card, if available
        code: prLn
      fullName:
        access: r
        type: string
        description: The full name from this participant's Contacts card, if available
        code: prFn
    identifiers:
      - property: id
        primary: true
  Account:
    name: Account
    plural: Accounts
    description: An account that can be logged in to from this system
    code: icsv
    properties:
      id:
        access: r
        type: string
        description: A unique identifier for this account.
        code: 'ID  '
      description:
        access: r
        type: string
        description: The name of this account as defined in Account preferences description field
        code: msdn
      enabled:
        access: rw
        type: boolean
        description: Is the account enabled?
        code: enbl
      connectionStatus:
        access: r
        type: string
        description: The connection status for this account.
        code: ssta
      serviceType:
        access: r
        type: string
        description: The type of service for this account
        code: styp
    identifiers:
      - property: id
        primary: true
  Chat:
    name: Chat
    plural: Chats
    description: An SMS or iMessage chat.
    code: imct
    properties:
      id:
        access: r
        type: string
        description: A guid identifier for this chat.
        code: 'ID  '
      name:
        access: r
        type: string
        description: The chat's name as it appears in the chat list.
        code: pnam
      account:
        access: r
        type:
          resource: account
        description: The account which is participating in this chat.
        code: icsv
    identifiers:
      - property: id
        primary: true
enums:
  ServiceType:
    name: ServiceType
    code: styp
    values:
      - name: sMS
        value: sMS
        code: ssms
      - name: iMessage
        value: iMessage
        code: sims
      - name: rCS
        value: rCS
        code: srcs
  Direction:
    name: Direction
    code: FTdr
    values:
      - name: incoming
        value: incoming
        code: FTic
      - name: outgoing
        value: outgoing
        code: FTog
  TransferStatus:
    name: TransferStatus
    code: FTst
    values:
      - name: preparing
        value: preparing
        code: FTsp
      - name: waiting
        value: waiting
        code: FTsw
      - name: transferring
        value: transferring
        code: FTsg
      - name: finalizing
        value: finalizing
        code: FTsz
      - name: finished
        value: finished
        code: FTsf
      - name: failed
        value: failed
        code: FTse
  ConnectionStatus:
    name: ConnectionStatus
    code: ssta
    values:
      - name: disconnecting
        value: disconnecting
        code: dcng
      - name: connected
        value: connected
        code: conn
      - name: connecting
        value: connecting
        code: cong
      - name: disconnected
        value: disconnected
        code: dcon
hierarchy:
  children:
    participants:
      resource: Participant
      access: r
      description: A participant for an account.
    accounts:
      resource: Account
      access: r
      description: An account that can be logged in to from this system
      children:
        chats:
          resource: Chat
          access: r
          description: An SMS or iMessage chat.
          children:
            participants:
              resource: Participant
              access: r
              description: A participant for an account.
        participants:
          resource: Participant
          access: r
          description: A participant for an account.
    chats:
      resource: Chat
      access: r
      description: An SMS or iMessage chat.
      children:
        participants:
          resource: Participant
          access: r
          description: A participant for an account.
commands:
  send:
    name: send
    description: Sends a message to a participant or to a chat.
    scope: application
    code: send
    parameters:
      - name: to
        type: string
        description: The to parameter
        required: true
        code: 'TO  '
  login:
    name: login
    description: Login to all accounts.
    scope: application
    code: logi
    parameters: []
  logout:
    name: logout
    description: Logout of all accounts.
    scope: application
    code: logo
    parameters: []
