/**
 * API plugin for Automator.app.
 *
 * Provides the manifest for registering RPC endpoints.
 *
 * @packageDocumentation
 */

import type { AppManifest } from '@macts/core'

/**
 * API plugin for Automator.app.
 *
 * This plugin contains the app manifest and metadata needed by the @macts/api
 * server to auto-generate RPC endpoints for Automator.app automation.
 */
export const automatorApiPlugin = {
  name: 'automator',
  bundleId: 'com.apple.Automator',
  manifest: {
    version: '1.0',
    app: {
      bundleId: 'com.apple.Automator',
      name: 'Automator',
      displayName: 'Automator',
      tccEntitlements: ['automation'],
      distributionModel: 'system',
    },
    suites: [
      {
        name: 'Standard Suite',
        description: 'Common classes and commands for all applications',
        code: '????',
        resources: [],
        commands: [],
        enums: [],
      },
      {
        name: 'Automator Suite',
        description: 'Terms and Events for controlling the Automator application',
        code: 'otto',
        resources: ['Workflow', 'AutomatorAction', 'Variable', 'Setting', 'RequiredResource'],
        commands: ['add', 'execute', 'remove'],
        enums: ['WarningLevel'],
      },
    ],
    resources: {
      Workflow: {
        name: 'Workflow',
        plural: 'Workflows',
        description: 'A series of actions stored in a file',
        code: 'wkfw',
        properties: {
          name: {
            access: 'r',
            type: 'string',
            description: 'The name of the workflow',
            code: 'pnam',
            optional: false,
          },
          currentAction: {
            access: 'r',
            type: 'any',
            description: 'The current or most recent action of the workflow',
            code: 'cact',
            optional: false,
          },
          executionResult: {
            access: 'r',
            type: 'any',
            description:
              'The result of the most recent execution; the output of the last action of that execution',
            code: 'xrsl',
            optional: false,
          },
          executionErrorMessage: {
            access: 'r',
            type: 'string',
            description: 'The text error message generated by the most recent execution',
            code: 'xerm',
            optional: false,
          },
          executionErrorNumber: {
            access: 'r',
            type: 'integer',
            description: 'The numeric error code generated by the most recent execution',
            code: 'xern',
            optional: false,
          },
          executionId: {
            access: 'r',
            type: 'string',
            description: 'The identifier of the current or most recent execution',
            code: 'xidx',
            optional: false,
          },
        },
        identifiers: [
          {
            property: 'name',
            primary: true,
          },
        ],
      },
      AutomatorAction: {
        name: 'AutomatorAction',
        plural: 'AutomatorActions',
        description: 'A single step in a workflow',
        code: 'actz',
        properties: {
          name: {
            access: 'r',
            type: 'string',
            description: 'The localized name of the action',
            code: 'pnam',
            optional: false,
          },
          bundleId: {
            access: 'r',
            type: 'string',
            description: 'The bundle identifier for the action',
            code: 'bnid',
            optional: false,
          },
          category: {
            access: 'r',
            type: {
              array: 'string',
            },
            description: 'The category that contains the action',
            code: 'ctgy',
            optional: false,
          },
          comment: {
            access: 'rw',
            type: 'string',
            description: 'The comment for the name of the action',
            code: 'comt',
            optional: false,
          },
          enabled: {
            access: 'rw',
            type: 'boolean',
            description: 'Is the action enabled?',
            code: 'enaB',
            optional: false,
          },
          executionErrorMessage: {
            access: 'r',
            type: 'string',
            description: 'The text error message generated by execution of the action',
            code: 'xerm',
            optional: false,
          },
          executionErrorNumber: {
            access: 'r',
            type: 'integer',
            description: 'The numeric error code generated by execution of the action',
            code: 'xern',
            optional: false,
          },
          executionResult: {
            access: 'r',
            type: 'any',
            description: 'The result of the action, passed as input to the next action',
            code: 'xrsl',
            optional: false,
          },
          iconName: {
            access: 'r',
            type: 'string',
            description: 'The icon name of the action',
            code: 'icnm',
            optional: false,
          },
          id: {
            access: 'r',
            type: 'string',
            description: 'The unique identifier for the action',
            code: 'ID  ',
            optional: false,
          },
          ignoresInput: {
            access: 'rw',
            type: 'boolean',
            description: 'Shall the action ignore its input when it is run?',
            code: 'igin',
            optional: false,
          },
          index: {
            access: 'rw',
            type: 'integer',
            description: 'The index of the action',
            code: 'pidx',
            optional: false,
          },
          inputTypes: {
            access: 'r',
            type: {
              array: 'string',
            },
            description: 'The input types accepted by the action',
            code: 'inty',
            optional: false,
          },
          keywords: {
            access: 'r',
            type: {
              array: 'string',
            },
            description: 'The keywords that describe the action',
            code: 'kywd',
            optional: false,
          },
          outputTypes: {
            access: 'r',
            type: {
              array: 'string',
            },
            description: 'The output types produced by the action',
            code: 'outy',
            optional: false,
          },
          parentWorkflow: {
            access: 'r',
            type: 'any',
            description: 'The workflow that contains the action',
            code: 'pwkf',
            optional: false,
          },
          path: {
            access: 'r',
            type: 'string',
            description: 'The path of the file that contains the action',
            code: 'ppth',
            optional: false,
          },
          showActionWhenRun: {
            access: 'rw',
            type: 'boolean',
            description: 'Shall the action show its user interface when it is run?',
            code: 'shwr',
            optional: false,
          },
          targetApplication: {
            access: 'r',
            type: {
              array: 'string',
            },
            description: 'The application with which the action communicates',
            code: 'tapp',
            optional: false,
          },
          version: {
            access: 'r',
            type: 'string',
            description: 'The version of the action',
            code: 'vers',
            optional: false,
          },
          warningAction: {
            access: 'r',
            type: 'string',
            description: 'The action suggested by the warning, if any',
            code: 'wact',
            optional: false,
          },
          warningLevel: {
            access: 'r',
            type: {
              enum: 'WarningLevel',
            },
            description: 'The level of the warning, increasing in likelihood of data loss',
            code: 'wlev',
            optional: false,
          },
          warningMessage: {
            access: 'r',
            type: 'string',
            description: 'The message that accompanies the warning, if any',
            code: 'wmsg',
            optional: false,
          },
        },
        identifiers: [
          {
            property: 'id',
            primary: true,
          },
        ],
      },
      Variable: {
        name: 'Variable',
        plural: 'Variables',
        description: 'A variable used by the workflow',
        code: 'vari',
        properties: {
          name: {
            access: 'rw',
            type: 'string',
            description: 'The name of the variable',
            code: 'pnam',
            optional: false,
          },
          value: {
            access: 'rw',
            type: 'any',
            description: 'The value of the variable',
            code: 'pval',
            optional: false,
          },
          settable: {
            access: 'r',
            type: 'boolean',
            description: 'Are the name and value of the variable settable?',
            code: 'stbl',
            optional: false,
          },
          id: {
            access: 'r',
            type: 'string',
            description: 'The unique identifier for the variable',
            code: 'ID  ',
            optional: false,
          },
        },
        identifiers: [
          {
            property: 'id',
            primary: true,
          },
        ],
      },
      Setting: {
        name: 'Setting',
        plural: 'Settings',
        description: 'A named value in an action',
        code: 'stng',
        properties: {
          name: {
            access: 'r',
            type: 'string',
            description: 'The name of the setting',
            code: 'pnam',
            optional: false,
          },
          value: {
            access: 'rw',
            type: 'any',
            description: 'The value of the setting',
            code: 'pval',
            optional: false,
          },
          defaultValue: {
            access: 'r',
            type: 'any',
            description: 'The default value of the setting',
            code: 'dval',
            optional: false,
          },
        },
        identifiers: [
          {
            property: 'name',
            primary: true,
          },
        ],
      },
      RequiredResource: {
        name: 'RequiredResource',
        plural: 'RequiredResources',
        description: 'A resource required for proper operation of the action',
        code: 'reqr',
        properties: {
          kind: {
            access: 'r',
            type: 'string',
            description: 'The kind of required resource',
            code: 'kind',
            optional: false,
          },
          name: {
            access: 'r',
            type: 'string',
            description: 'The name of the required resource',
            code: 'pnam',
            optional: false,
          },
          resource: {
            access: 'r',
            type: 'string',
            description: 'The specification of the required resource',
            code: 'rsrc',
            optional: false,
          },
          version: {
            access: 'r',
            type: 'integer',
            description: 'The minimum acceptable version of the required resource',
            code: 'vers',
            optional: false,
          },
        },
        identifiers: [
          {
            property: 'name',
            primary: true,
          },
        ],
      },
    },
    enums: {
      WarningLevel: {
        name: 'WarningLevel',
        description: 'The level of warning for an action',
        code: 'wlev',
        values: [
          {
            name: 'none',
            value: 'none',
            description: 'No warning',
            code: 'none',
          },
          {
            name: 'reversible',
            value: 'reversible',
            description: 'Reversible action',
            code: 'rvbl',
          },
          {
            name: 'irreversible',
            value: 'irreversible',
            description: 'Irreversible action',
            code: 'irrv',
          },
        ],
      },
    },
    hierarchy: {
      children: {
        workflows: {
          resource: 'Workflow',
          access: 'rw',
          description: 'Workflows in the application',
          children: {
            actions: {
              resource: 'AutomatorAction',
              access: 'rw',
              description: 'Actions within a workflow',
              children: {
                settings: {
                  resource: 'Setting',
                  access: 'rw',
                  description: 'Settings for an action',
                },
                requiredResources: {
                  resource: 'RequiredResource',
                  access: 'r',
                  description: 'Required resources for an action',
                },
              },
            },
            variables: {
              resource: 'Variable',
              access: 'rw',
              description: 'Variables within a workflow',
            },
          },
        },
      },
    },
    relationships: [],
    commands: {
      list: {
        name: 'list',
        description: 'List all workflows',
        scope: 'resource',
        resourceType: 'Workflow',
        parameters: [],
        code: 'core',
        permission: 'automator:workflows:list',
      },
      get: {
        name: 'get',
        description: 'Get a workflow by name',
        scope: 'resource',
        resourceType: 'Workflow',
        parameters: [
          {
            name: 'name',
            type: 'string',
            description: 'Workflow name',
            required: true,
          },
        ],
        code: 'getd',
        permission: 'automator:workflows:get',
      },
      execute: {
        name: 'execute',
        description: 'Execute a workflow',
        scope: 'resource',
        resourceType: 'Workflow',
        parameters: [
          {
            name: 'workflow',
            type: 'any',
            description: 'The workflow to execute',
            required: true,
          },
        ],
        code: 'exec',
        permission: 'automator:workflows:execute',
      },
      listActions: {
        name: 'list',
        description: 'List all actions in a workflow',
        scope: 'resource',
        resourceType: 'AutomatorAction',
        parameters: [
          {
            name: 'workflowName',
            type: 'string',
            description: 'Workflow name',
            required: true,
          },
        ],
        code: 'core',
        permission: 'automator:actions:list',
      },
      getAction: {
        name: 'get',
        description: 'Get an action by ID',
        scope: 'resource',
        resourceType: 'AutomatorAction',
        parameters: [
          {
            name: 'id',
            type: 'string',
            description: 'Action identifier',
            required: true,
          },
        ],
        code: 'getd',
        permission: 'automator:actions:get',
      },
      add: {
        name: 'add',
        description: 'Add an Automator action or variable to a workflow',
        scope: 'application',
        parameters: [
          {
            name: 'object',
            type: 'any',
            description: 'The Automator action or variable to add',
            required: true,
          },
          {
            name: 'to',
            type: 'any',
            description: 'The workflow to which the action or variable is to be added',
            required: true,
            code: 'insh',
          },
          {
            name: 'atIndex',
            type: 'integer',
            description: 'The index at which the action or variable is to be added',
            required: false,
            code: 'at I',
          },
        ],
        code: 'add ',
        permission: 'automator:workflows:add',
      },
      remove: {
        name: 'remove',
        description: 'Remove an Automator action or variable from a workflow',
        scope: 'application',
        parameters: [
          {
            name: 'object',
            type: 'any',
            description: 'The Automator action or variable to remove',
            required: true,
          },
        ],
        code: 'remv',
        permission: 'automator:workflows:remove',
      },
      listVariables: {
        name: 'list',
        description: 'List all variables in a workflow',
        scope: 'resource',
        resourceType: 'Variable',
        parameters: [
          {
            name: 'workflowName',
            type: 'string',
            description: 'Workflow name',
            required: true,
          },
        ],
        code: 'core',
        permission: 'automator:variables:list',
      },
      getVariable: {
        name: 'get',
        description: 'Get a variable by ID',
        scope: 'resource',
        resourceType: 'Variable',
        parameters: [
          {
            name: 'id',
            type: 'string',
            description: 'Variable identifier',
            required: true,
          },
        ],
        code: 'getd',
        permission: 'automator:variables:get',
      },
      listSettings: {
        name: 'list',
        description: 'List all settings for an action',
        scope: 'resource',
        resourceType: 'Setting',
        parameters: [
          {
            name: 'actionId',
            type: 'string',
            description: 'Action identifier',
            required: true,
          },
        ],
        code: 'core',
        permission: 'automator:settings:list',
      },
      getSetting: {
        name: 'get',
        description: 'Get a setting by name',
        scope: 'resource',
        resourceType: 'Setting',
        parameters: [
          {
            name: 'name',
            type: 'string',
            description: 'Setting name',
            required: true,
          },
        ],
        code: 'getd',
        permission: 'automator:settings:get',
      },
      listRequiredResources: {
        name: 'list',
        description: 'List all required resources for an action',
        scope: 'resource',
        resourceType: 'RequiredResource',
        parameters: [
          {
            name: 'actionId',
            type: 'string',
            description: 'Action identifier',
            required: true,
          },
        ],
        code: 'core',
        permission: 'automator:requiredResources:list',
      },
      getRequiredResource: {
        name: 'get',
        description: 'Get a required resource by name',
        scope: 'resource',
        resourceType: 'RequiredResource',
        parameters: [
          {
            name: 'name',
            type: 'string',
            description: 'Resource name',
            required: true,
          },
        ],
        code: 'getd',
        permission: 'automator:requiredResources:get',
      },
    },
    permissions: {
      workflows: {
        read: ['automator:workflows:list', 'automator:workflows:get'],
        create: ['automator:workflows:create'],
        write: [
          'automator:workflows:update',
          'automator:workflows:execute',
          'automator:workflows:add',
          'automator:workflows:remove',
        ],
        delete: ['automator:workflows:delete'],
      },
      actions: {
        read: ['automator:actions:list', 'automator:actions:get'],
        create: ['automator:actions:create'],
        write: ['automator:actions:update'],
        delete: ['automator:actions:delete'],
      },
      variables: {
        read: ['automator:variables:list', 'automator:variables:get'],
        create: ['automator:variables:create'],
        write: ['automator:variables:update'],
        delete: ['automator:variables:delete'],
      },
      settings: {
        read: ['automator:settings:list', 'automator:settings:get'],
        write: ['automator:settings:update'],
      },
      requiredResources: {
        read: ['automator:requiredResources:list', 'automator:requiredResources:get'],
      },
    },
    extraction: {
      sourceFile: 'Automator.scriptSuite + Automator.scriptTerminology',
      confidence: {
        overall: 0.95,
        fields: {
          resources: 1,
          enums: 1,
          hierarchy: 0.95,
          commands: 0.95,
        },
      },
      openQuestions: [],
    },
  } as AppManifest,
} as const
