/**
 * AnalyzerIssue client for Xcode SDK.
 * Auto-generated - do not edit.
 */

import type { HttpClient } from '../client.js'
import type { AnalyzerIssue, AnalyzerIssueCreateInput, AnalyzerIssueUpdateInput } from '../types.js'

/**
 * Client for a warning generated by the static analyzer.
 */
export class AnalyzerIssueResourceClient {
  readonly #http: HttpClient
  readonly #app: string
  readonly #resource: string

  constructor(http: HttpClient, app: string, resource: string) {
    this.#http = http
    this.#app = app
    this.#resource = resource
  }

  /**
   * List all analyzerissues.
   */
  async list(): Promise<AnalyzerIssue[]> {
    return this.#http.rpc<AnalyzerIssue[]>(`${this.#app}.${this.#resource}.list`)
  }

  /**
   * Get a analyzerissue by message.
   */
  async get(message: string): Promise<AnalyzerIssue> {
    return this.#http.rpc<AnalyzerIssue>(`${this.#app}.${this.#resource}.get`, { message })
  }

  /**
   * Create a new analyzerissue.
   */
  async create(input: AnalyzerIssueCreateInput): Promise<AnalyzerIssue> {
    return this.#http.rpc<AnalyzerIssue>(`${this.#app}.${this.#resource}.create`, input)
  }

  /**
   * Update an existing analyzerissue.
   */
  async update(message: string, input: AnalyzerIssueUpdateInput): Promise<AnalyzerIssue> {
    return this.#http.rpc<AnalyzerIssue>(`${this.#app}.${this.#resource}.update`, {
      message,
      ...input,
    })
  }

  /**
   * Delete a analyzerissue.
   */
  async delete(message: string): Promise<void> {
    await this.#http.rpc<undefined>(`${this.#app}.${this.#resource}.delete`, { message })
  }
}
