/**
 * BuildWarning client for Xcode SDK.
 * Auto-generated - do not edit.
 */

import type { HttpClient } from '../client.js';
import type { BuildWarning, BuildWarningCreateInput, BuildWarningUpdateInput } from '../types.js';

/**
 * Client for a warning generated by a build.
 */
export class BuildWarningResourceClient {
  readonly #http: HttpClient;
  readonly #app: string;
  readonly #resource: string;

  constructor(http: HttpClient, app: string, resource: string) {
    this.#http = http;
    this.#app = app;
    this.#resource = resource;
  }

  /**
   * List all buildwarnings.
   */
  async list(): Promise<BuildWarning[]> {
    return this.#http.rpc<BuildWarning[]>(`${this.#app}.${this.#resource}.list`);
  }

  /**
   * Get a buildwarning by message.
   */
  async get(message: string): Promise<BuildWarning> {
    return this.#http.rpc<BuildWarning>(`${this.#app}.${this.#resource}.get`, { message });
  }

  /**
   * Create a new buildwarning.
   */
  async create(input: BuildWarningCreateInput): Promise<BuildWarning> {
    return this.#http.rpc<BuildWarning>(`${this.#app}.${this.#resource}.create`, input);
  }

  /**
   * Update an existing buildwarning.
   */
  async update(message: string, input: BuildWarningUpdateInput): Promise<BuildWarning> {
    return this.#http.rpc<BuildWarning>(`${this.#app}.${this.#resource}.update`, { message, ...input });
  }

  /**
   * Delete a buildwarning.
   */
  async delete(message: string): Promise<void> {
    return this.#http.rpc<void>(`${this.#app}.${this.#resource}.delete`, { message });
  }

}
