/**
 * BuildError client for Xcode SDK.
 * Auto-generated - do not edit.
 */

import type { HttpClient } from '../client.js';
import type { BuildError, BuildErrorCreateInput, BuildErrorUpdateInput } from '../types.js';

/**
 * Client for an error generated by a build.
 */
export class BuildErrorResourceClient {
  readonly #http: HttpClient;
  readonly #app: string;
  readonly #resource: string;

  constructor(http: HttpClient, app: string, resource: string) {
    this.#http = http;
    this.#app = app;
    this.#resource = resource;
  }

  /**
   * List all builderrors.
   */
  async list(): Promise<BuildError[]> {
    return this.#http.rpc<BuildError[]>(`${this.#app}.${this.#resource}.list`);
  }

  /**
   * Get a builderror by message.
   */
  async get(message: string): Promise<BuildError> {
    return this.#http.rpc<BuildError>(`${this.#app}.${this.#resource}.get`, { message });
  }

  /**
   * Create a new builderror.
   */
  async create(input: BuildErrorCreateInput): Promise<BuildError> {
    return this.#http.rpc<BuildError>(`${this.#app}.${this.#resource}.create`, input);
  }

  /**
   * Update an existing builderror.
   */
  async update(message: string, input: BuildErrorUpdateInput): Promise<BuildError> {
    return this.#http.rpc<BuildError>(`${this.#app}.${this.#resource}.update`, { message, ...input });
  }

  /**
   * Delete a builderror.
   */
  async delete(message: string): Promise<void> {
    return this.#http.rpc<void>(`${this.#app}.${this.#resource}.delete`, { message });
  }

}
