/**
 * Type definitions for the SDK.
 * Auto-generated - do not edit.
 */

import { z } from 'zod'

/** The level of warning for an action */
export type WarningLevel = 'none' | 'reversible' | 'irreversible'

/** A series of actions stored in a file */
export interface Workflow {
  /** Canonical identifier (mirrors `name`); populated by list, pass to get/delete and to write operations that reference this resource. */
  id?: string
  /** The name of the workflow */
  name: string
  /** The current or most recent action of the workflow */
  currentAction: unknown
  /** The result of the most recent execution; the output of the last action of that execution */
  executionResult: unknown
  /** The text error message generated by the most recent execution */
  executionErrorMessage: string
  /** The numeric error code generated by the most recent execution */
  executionErrorNumber: number
  /** The identifier of the current or most recent execution */
  executionId: string
}

/** Input for creating a Workflow */
export type WorkflowCreateInput = Record<string, never>

/** Input for updating a Workflow */
export type WorkflowUpdateInput = Partial<WorkflowCreateInput>

/** A single step in a workflow */
export interface AutomatorAction {
  /** The localized name of the action */
  name: string
  /** The bundle identifier for the action */
  bundleId: string
  /** The category that contains the action */
  category: string[]
  /** The comment for the name of the action */
  comment: string
  /** Is the action enabled? */
  enabled: boolean
  /** The text error message generated by execution of the action */
  executionErrorMessage: string
  /** The numeric error code generated by execution of the action */
  executionErrorNumber: number
  /** The result of the action, passed as input to the next action */
  executionResult: unknown
  /** The icon name of the action */
  iconName: string
  /** The unique identifier for the action */
  id: string
  /** Shall the action ignore its input when it is run? */
  ignoresInput: boolean
  /** The index of the action */
  index: number
  /** The input types accepted by the action */
  inputTypes: string[]
  /** The keywords that describe the action */
  keywords: string[]
  /** The output types produced by the action */
  outputTypes: string[]
  /** The workflow that contains the action */
  parentWorkflow: unknown
  /** The path of the file that contains the action */
  path: string
  /** Shall the action show its user interface when it is run? */
  showActionWhenRun: boolean
  /** The application with which the action communicates */
  targetApplication: string[]
  /** The version of the action */
  version: string
  /** The action suggested by the warning, if any */
  warningAction: string
  /** The level of the warning, increasing in likelihood of data loss */
  warningLevel: WarningLevel
  /** The message that accompanies the warning, if any */
  warningMessage: string
}

/** Input for creating a AutomatorAction */
export interface AutomatorActionCreateInput {
  /** The comment for the name of the action */
  comment?: string
  /** Is the action enabled? */
  enabled?: boolean
  /** Shall the action ignore its input when it is run? */
  ignoresInput?: boolean
  /** The index of the action */
  index?: number
  /** Shall the action show its user interface when it is run? */
  showActionWhenRun?: boolean
}

/** Input for updating a AutomatorAction */
export type AutomatorActionUpdateInput = Partial<AutomatorActionCreateInput>

/** A variable used by the workflow */
export interface Variable {
  /** The name of the variable */
  name: string
  /** The value of the variable */
  value: unknown
  /** Are the name and value of the variable settable? */
  settable: boolean
  /** The unique identifier for the variable */
  id: string
}

/** Input for creating a Variable */
export interface VariableCreateInput {
  /** The name of the variable */
  name?: string
  /** The value of the variable */
  value?: unknown
}

/** Input for updating a Variable */
export type VariableUpdateInput = Partial<VariableCreateInput>

/** A named value in an action */
export interface Setting {
  /** Canonical identifier (mirrors `name`); populated by list, pass to get/delete and to write operations that reference this resource. */
  id?: string
  /** The name of the setting */
  name: string
  /** The value of the setting */
  value: unknown
  /** The default value of the setting */
  defaultValue: unknown
}

/** Input for creating a Setting */
export interface SettingCreateInput {
  /** The value of the setting */
  value?: unknown
}

/** Input for updating a Setting */
export type SettingUpdateInput = Partial<SettingCreateInput>

/** A resource required for proper operation of the action */
export interface RequiredResource {
  /** Canonical identifier (mirrors `name`); populated by list, pass to get/delete and to write operations that reference this resource. */
  id?: string
  /** The kind of required resource */
  kind: string
  /** The name of the required resource */
  name: string
  /** The specification of the required resource */
  resource: string
  /** The minimum acceptable version of the required resource */
  version: number
}

/** Input for creating a RequiredResource */
export type RequiredResourceCreateInput = Record<string, never>

/** Input for updating a RequiredResource */
export type RequiredResourceUpdateInput = Partial<RequiredResourceCreateInput>

// Zod schemas for runtime validation

export const WorkflowSchema = z.object({
  id: z.string().optional(),
  name: z.string(),
  currentAction: z.unknown(),
  executionResult: z.unknown(),
  executionErrorMessage: z.string(),
  executionErrorNumber: z.number(),
  executionId: z.string(),
})

export const AutomatorActionSchema = z.object({
  name: z.string(),
  bundleId: z.string(),
  category: z.array(z.string()),
  comment: z.string(),
  enabled: z.boolean(),
  executionErrorMessage: z.string(),
  executionErrorNumber: z.number(),
  executionResult: z.unknown(),
  iconName: z.string(),
  id: z.string(),
  ignoresInput: z.boolean(),
  index: z.number(),
  inputTypes: z.array(z.string()),
  keywords: z.array(z.string()),
  outputTypes: z.array(z.string()),
  parentWorkflow: z.unknown(),
  path: z.string(),
  showActionWhenRun: z.boolean(),
  targetApplication: z.array(z.string()),
  version: z.string(),
  warningAction: z.string(),
  warningLevel: z.string(),
  warningMessage: z.string(),
})

export const VariableSchema = z.object({
  name: z.string(),
  value: z.unknown(),
  settable: z.boolean(),
  id: z.string(),
})

export const SettingSchema = z.object({
  id: z.string().optional(),
  name: z.string(),
  value: z.unknown(),
  defaultValue: z.unknown(),
})

export const RequiredResourceSchema = z.object({
  id: z.string().optional(),
  kind: z.string(),
  name: z.string(),
  resource: z.string(),
  version: z.number(),
})
