/**
 * TypeScript SDK for macOS Calendar.app automation.
 *
 * This file is generated by the macts SDK generator.
 * Do not edit manually - changes will be overwritten.
 *
 * To regenerate this SDK, run:
 *   macts generate sdk-calendar
 *
 * @packageDocumentation
 */

/**
 * Placeholder export to prevent empty module errors.
 * This will be replaced by generated SDK code.
 */
export const SDK_PLACEHOLDER = 'Generated SDK code will appear here';
